version: "3.6"

services:
  frontend:
    container_name: ${PROJECT_NAME}
    image: node:14-alpine
    env_file:
      - .env
    ports:
      - "127.0.0.1:${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - default
    command: sh -c "cd /var/www/html && yarn install && ( yarn run dev & node /var/www/html/index.js ) && fg"
    volumes:
      - ./frontend:/var/www/html
    restart: unless-stopped
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24