version: "3"

services:
  frontend:
    container_name: ${PROJECT_NAME}_frontend
    image: node:14-alpine
    env_file:
      - .env
    ports:
      - "127.0.0.1:${HOST_FRONTEND_PORT}:${FRONTEND_PORT}"
    entrypoint: ""
    command: sh -c "cd /var/www/html && yarn install && ( yarn run dev & node /var/www/html/index.js ) && fg"
    volumes:
      - ./frontend:/var/www/html
    restart: on-failure
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24